# Generated by Django 3.2.11 on 2022-02-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lisenceplate',
            name='time_create',
        ),
        migrations.AddField(
            model_name='lisenceplate',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lisenceplate',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lisenceplate',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
